services:
  - type: web
    name: portfolio
    runtime: java  # This ensures Java is installed
    buildCommand: |
      cd Portfoli && npm install && npm run build
      cd ../Portfolio-backend && ./mvnw.cmd clean package
      cp -r ../Portfoli/dist/portfoli/* src/main/resources/static/
    startCommand: ./mvnw.cmd spring-boot:run -Dspring-boot.run.profiles=production -Dserver.port=$PORT
    env: java
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: lottringt12018@gmail.com
      - key: SMTP_PASSWORD
        generateValue: true  # You should set this as a secret in Render dashboard
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
    staticAssets:
      - path: Portfolio-backend/src/main/resources/static
        destination: /