services:
  - type: web
    name: portfolio
    runtime: java
    buildCommand: |
      echo "===== BUILD START ====="
      
      # Build Angular frontend
      echo "Building frontend..."
      cd Portfoli
      npm install
      npm run build
      
      # Build Spring Boot backend
      echo "Building backend..."
      cd ../Portfolio-backend
      chmod +x mvnw
      ./mvnw clean package
      
      # Verify JAR file was created
      if [ ! -f "target/Portfolio-backend-*.jar" ]; then
        echo "❌ Error: JAR file not found!"
        ls -la target/
        exit 1
      fi
      
      # Copy frontend to static resources
      echo "Copying frontend files..."
      mkdir -p src/main/resources/static
      cp -r ../Portfoli/dist/portfoli/* src/main/resources/static/
      
      echo "===== BUILD COMPLETE ====="
    startCommand: |
      echo "===== STARTING APPLICATION ====="
      cd Portfolio-backend
      JAR_FILE=$(ls target/*.jar | head -n 1)
      echo "Running JAR: $JAR_FILE"
      java -Dserver.port=$PORT -Dspring.profiles.active=production -jar "$JAR_FILE"
    env: java
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: lottringt12018@gmail.com
      - key: SMTP_PASSWORD
        generateValue: true
    staticAssets:
      - path: Portfolio-backend/src/main/resources/static
        destination: /