services:
  - type: web
    name: portfolio
    runtime: java
    buildCommand: |
      cd Portfoli && npm install && npm run build
      cd ../Portfolio-backend && chmod +x mvnw && ./mvnw clean package
      cp -r ../Portfoli/dist/portfoli/* src/main/resources/static/
    startCommand: java -Dserver.port=$PORT -jar target/Portfolio-backend-0.0.1-SNAPSHOT.jar
    env: java
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: lottringt12018@gmail.com
      - key: SMTP_PASSWORD
        generateValue: true # You should set this as a secret in Render dashboard
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
    staticAssets:
      - path: Portfolio-backend/src/main/resources/static
        destination: /
