services:
  - type: web
    name: portfolio
    buildCommand: |
      echo "==== BUILD START ===="

      cd Portfoli
      npm install
      npm run build

      cd ../Portfolio-backend
      mvn clean package

      mkdir -p src/main/resources/static
      cp -r ../Portfoli/dist/portfoli/* src/main/resources/static

      echo "==== BUILD DONE ===="
    startCommand: |
      cd Portfolio-backend
      java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: lottringt12018@gmail.com
      - key: SMTP_PASSWORD
        generateValue: true
