services:
  - type: web
    name: portfolio
    runtime: java
    buildCommand: |
      cd Portfoli && npm install && npm run build
      cd ../Portfolio-backend && chmod +x mvnw && ./mvnw clean package
      cp -r ../Portfoli/dist/portfoli/* src/main/resources/static/
    startCommand: |
      # Set explicit Java path (Render uses Ubuntu Linux)
      JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
      
      # Verify Java is available
      if [ ! -d "$JAVA_HOME" ]; then
        echo "❌ Java not found at $JAVA_HOME"
        exit 1
      fi
      
      # Start Spring Boot with production profile
      echo "🚀 Starting Java application..."
      $JAVA_HOME/bin/java -version
      $JAVA_HOME/bin/java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/Portfolio-backend-*.jar
    env: java
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: lottringt12018@gmail.com
      - key: SMTP_PASSWORD
        generateValue: true # You should set this as a secret in Render dashboard
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
    staticAssets:
      - path: Portfolio-backend/src/main/resources/static
        destination: /
